[package]
name = "swap"
version = "0.0.1"
edition = "2024"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
candid = "0.10.12"
ic-cdk = "0.17.1"

serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"

strum = "0.26.3"
strum_macros = "0.26.4"
