// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EncodedBlock {
    #[prost(bytes = "bytes", tag = "1")]
    pub block: ::prost::bytes::Bytes,
}
/// Get a single block
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetBlockRequest {
    #[prost(uint64, tag = "1")]
    pub block_height: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockResponse {
    #[prost(message, optional, tag = "1")]
    pub block: ::core::option::Option<EncodedBlock>,
}
/// Get many blocks
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetBlocksRequest {
    #[prost(uint64, tag = "1")]
    pub start: u64,
    #[prost(uint64, tag = "2")]
    pub length: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlocksResponse {
    #[prost(message, repeated, tag = "1")]
    pub blocks: ::prost::alloc::vec::Vec<EncodedBlock>,
}
