[package]
name = "common"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"
# crate-type = ["cdylib"] # rust lib 包不能是 cdylib, 否则不能被引入

[lints]
workspace = true

[dependencies]
candid = { workspace = true }

serde = { workspace = true }
serde_bytes = { workspace = true }

hex = { workspace = true }

prost = "0.13.5" # 处理 protobuf 的代码

[build-dependencies]
prost-build = "0.13.5" # 编译 protobuf build依赖
